---

# Override birt-viewer role defaults
apache:
  server_name: "localhost" # ServerName e.g. myserver.domain.com
  allow_ip: "83.150.108.249" # Allow http connections from
  sslcert: '/etc/ssl/certs/ssl-cert-snakeoil.pem'
  sslkey: '/etc/ssl/private/ssl-cert-snakeoil.key'
  # sslchain: '/etc/ssl/forgeservicela1b.fi.crt.chain'


# Override birt-reports role defaults
birt_reports:
  user:
    name: birt
    auth_keys:
      - 'auth_key.pub'
#      - 'auth_jenkins.pub'
  repo_access_key: git_access_key
  repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge/forge-birt-reportdesigns.git
  connection_profile:
    - name: iaas
      src: iaas_development
      dst: iaas_db

    - name: redmine
      src: redmine_development
      dst: redmine_db
  
# Override resource-usage-reporting-ansible role defaults
datasource:
  user: 
    name: "birt"
    auth_keys:
      - 'auth_key.pub'
  os:
    auth_url: "https://cloud.forgeservicelab.fi:5001/v2.0"
    tenant_id: "YOUR OPENSTACK TENANT ID"
    tenant_name: "YOUR OPENSTACK TENANT NAME"
    username: "YOUR OPENSTACK USERNAME"
    password: "YOUR OPENSTACK PASSWORD"
  app:
    repo: "ssh://gitlab@git.forgeservicelab.fi:10022/forge/resource-usage-reporting.git"
    repo_key: "git_access_key"
    dest: "/home/birt/bin/resource-usage-reporting"      
  db: 
    user: "birt"
    name: "iaas_development"
    host: "localhost"
    password: "YOUR DESIRED PSQL PASSWORD"
    defaults:
      capacity:
        vcpus: "1312"
        memory: "4112384"
        volume: "65536"

# Veriables for tasks/postgresql.yml
web_domain: "{{ ansible_ssh_host }}"

postgresql_users:
  - name: "birt"
    pass: "YOUR DESIRED PSQL PASSWORD"
    encrypted: yes

postgresql_databases:
  - name: "iaas_development"
    hstore: yes
    uuid-ossp: yes
    owner: birt

postgresql_user_privileges:
  - name: "birt"
    db: "iaas_development"
    priv: "ALL"

postgresql_listen_addresses:
  - 0.0.0.0

postgresql_log_destination: syslog

postgresql_logging_collector: on

postgresql_authentication:
  - type: hostssl
    user: "birt"
    method: md5
    database: "iaas_development"
    address:  83.150.108.249/32

  - type: hostssl
    user: "birt"
    method: md5
    database: "iaas_development"
    address:  "{{ inventory_hostname }}/32"

postgresql_ssl: on
postgresql_ssl_cert_file: "{{ apache.sslcert }}"
postgresql_ssl_key_file: "{{ apache.sslkey }}"
